/*
 * config.h
 *
 *  Created on: Oct 11, 2023
 *      Author: soft
 */

#ifndef INC_CONFIG_H_
#define INC_CONFIG_H_

#define PRIVATE CANTP_DEV_ERROR_DETECT STD_ON
#define CANTP_SW_VERSION_MAJOR 1
#define CANTP_SW_VERSION_MINOR 0
#define CANTP_SW_VERSION_PATCH 0
#define CANTP_AR_RELEASE_MAJOR_VERSION 4 // SWS_BSW_00059
#define CANTP_AR_RELEASE_MINOR_VERSION 4
#define CANTP_API STD_ON
#define CANTP_GET_VERSION_INFO_API STD_ON // ECUC_CanTp_00283
#define CANTP_CHANGE_PARAMETER_API STD_ON // ECUC_CanTp_00299
#define CANTP_READ_PARAMETER_API STD_ON // ECUC_CanTp_00300
#define OS_GET_TIME_API STD_OFF

#endif /* INC_CONFIG_H_ */
